version: '3.8'
services:
  react-app:
    build: .
    ports:
      # - '3000:3000'
      - "5173:5173"  # Ensure this port mapping is there
    command: npm run dev -- --host 0.0.0.0  # Add --host to expose to all network interfaces
